name: Download Terraform Remote State

on:
  workflow_dispatch:

jobs:
  download-state:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1
    - name: check 1
      run: ls -la
    - name: Download remote state file
      run: |
        echo "Fetching remote state file from S3..."
        aws s3 cp s3://bucketforterraformangit/develop/terraform.tfstate .
   

    - name: Check
      run: ls -la
    - name: cat 
      run: cat terraform.tfstate
    - name: Login to Terraform Cloud
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Initialize Terraform
      run: 
        terraform init 
           
    - name: Check2
      run: ls -la
    - name: Push state to Terraform Cloud
      run: |
        echo "Pushing state to Terraform Cloud..."

        terraform state push -force terraform.tfstate 

