name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Terraform Cloud
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

    - name: Configure Terraform Cloud
      run: |
        echo "Setting up Terraform Cloud authentication..."
        echo "TFC_TOKEN=${{ secrets.TF_CLOUD_TOKEN }}" >> $GITHUB_ENV
        echo "TFC_ORGANIZATION=terraform-rayah" >> $GITHUB_ENV
        echo "TFC_WORKSPACE=my-new-workspace" >> $GITHUB_ENV

    - name: Get Terraform state
      run: |
        echo "Retrieving Terraform state from Terraform Cloud..."
        terraform init -backend-config="token=${TFC_TOKEN}" -backend-config="organization=${TFC_ORGANIZATION}" -backend-config="workspaces.name=${TFC_WORKSPACE}"

    - name: Destroy infrastructure
      run: terraform destroy -auto-approve
