name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Terraform Cloud
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Configure Terraform Cloud backend
        run: |
          echo "terraform {
            backend \"remote\" {
              organization = \"terraform-rayah\"
              workspaces {
                name = \"my-new-workspace\"
              }
            }
          }" > override.tf

      - name: Terraform init
        run: terraform init

      - name: Destroy infrastructure
        run: terraform destroy -auto-approve
