name: Download Terraform Remote State Final

on:
  workflow_dispatch:

jobs:
  download-state:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: us-east-1

    - name: Login to Terraform Cloud
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}


    - name: Configure Terraform Cloud backend
      run: |
        echo "terraform {
          backend \"remote\" {
            organization = \"terraform-rayah\"
            workspaces {
              name = \"my-new-workspace\"
            }
          }
        }" > override.tf
    - name: check 1
      run: ls -la
    - name: check 333
      run: cat override.tf
  

    
    - name: Terraform init
      run: terraform init 


    # - name: terraform apply
    #   run: terraform apply -auto-approve
    - name: Download remote state file
      run: |
          echo "Fetching remote state file from S3..."
          aws s3 cp s3://bucketforterraformangit/terraform.tfstate .

    - name: check 2
      run: ls -la
    - name: Push state to Terraform Cloud
      run: |
        terraform state push terraform.tfstate