name: Migrate Backend to Terraform Cloud

on:
  workflow_dispatch:


jobs:
  Migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: COnfig -backend-config
        run: |
          terraform init \
            -backend-config="bucket=bucketforterraformangit" \
            -backend-config="key=develop/terraform.tfstate" \
            -backend-config="region=us-east-1"
          terraform state pull > terraform.tfstate

      - name: Configure Remote Backend
        run: |
          export TF_CLOUD_TOKEN=${{ secrets.TF_CLOUD_TOKEN }}
          terraform init \
            -backend=remote \
            -backend-config="hostname=app.terraform.io" \
            -backend-config="organization=terraform-rayah" \
            -backend-config="token=${TF_CLOUD_TOKEN}" \
            -backend-config="workspaces.name=my-new-workspace"
          terraform state push terraform.tfstate
            

 




