name: Migrate  

on:
  workflow_dispatch:
 

        
jobs:
  Migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1
   
    - name: Setup Terraform Cloud Credentials
      uses: hashicorp/setup-terraform@v2
      with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Initialize Terraform
      run: terraform init -backend-config="bucket=bucketforterraformangit" -backend-config="key=develop/terraform.tfstate" -backend-config="region=us-east-1"
  
    - name: pull
      run: |
           terraform state pull > terraform.tfstate
    - name: CHeck 
      run: |
         ls -la 
    - name: Check 2
      run: cat terraform.tfstate

    - name: Print working directory and file path
      run: |
         echo "Working directory: $(pwd)"
          echo "File path: $(ls -la terraform.tfstate)"


    - name: Migrate state to Terraform Cloud
      run: terraform state push  /home/runner/work/letsdosometerraform/letsdosometerraform/terraform.tfstate

