name: Migrate Backend to Terraform Cloud

on:
  workflow_dispatch:


jobs:
  Migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Configure Terraform Cloud credentials
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          cli_config_credentials_hostname: GitTerraform
      - name: Init Terraform
        run: terraform init
      - name: Migrate state
        run: |
          terraform state pull -out=backup.tfstate
          terraform state push -backup=backup.tfstate




