name: Terraform State Pull

on:
  workflow_dispatch:
    

jobs:
  pull-state:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Check2
      run: ls -la
    - name: Download Terraform state from S3
      run: |
        aws s3 cp s3://bucketforterraformangit/develop/terraform.tfstate .
    - name: Check2
      run: ls -la  

    - name: Terraform Init
      run: terraform init -backend-config=bucket=bucket=bucketforterraformangit -backend-config=key=terraform.tfstate -reconfigure
    - name: Terraform State Pull
      run: terraform state pull
    # - name: Check2
    #   run: ls -la
